name: CI/CD Pipeline
on: [push]
jobs: 
  Pipelining: 
    runs-on: ubuntu-18.04
    steps: 
      - 
        name: "SSH auth"
        run: "echo \"ssh auth in progress\""
      - 
        name: "executing remote ssh commands using password"
        uses: appleboy/ssh-action@master
        with: 
          host: "${{ secrets.IP_ADD }}"
          key: "${{ secrets.P_KEY }}"
          username: "${{ secrets.USER }}"
          script: |
            cd crop-recommender-Azure
            git pull origin master
            cd frontend
            printf 'REACT_APP_BACKEND_URL="${{ secrets.IP_ADD }}"' > .env
            npm run build
            cd ../backend
            source venv/bin/activate
            printf '${{ secrets.BE_ENV }}' > .env
            PID=`ps aux | grep flask | grep -v grep | awk '{print $2}' | head -n 1`
            if [[ "" !=  "$PID" ]]; then
              echo "killing $PID"
              kill -9 $PID
            fi
            nohup flask run --host=0.0.0.0 &
            